publisher/urls.py
from django.conf.urls import url

from . import views

app_name = 'publisher'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'register/$', views.register, name='register'),
    url(r'success/$', views.success, name='success'),
    url(r'create_bulletin/$', views.create_bulletin, name='create'),
    url(r'alter_bulletin/$', views.alter_bulletin, name='alter_bulletin'),
    url(r'^delete/(?P<bulletin_id>\d+)/$', views.delete_bulletin, name='delete'),
    url(r'^batchUpload/$', views.batch_import_bulletin_by_excel, name='batchUpload'),
]

users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^hospital/$', views.hospital, name='hospital'),
    url(r'^department/$', views.department, name='department'),
    url(r'^test/$', views.test, name='test'),
    url(r'^doctor/$', views.doctor, name='doctor'),
    url(r'^reservation/$', views.reservation, name='reservation'),
    url(r'^usercenter/$', views.user_center, name='usercenter'),
    url(r'^usercenter/changeinfo/$', views.change_info, name='changeinfo'),
    url(r'^usercenter/accountsafe/$', views.change_pw, name='accountsafe'),
    url(r'^usercenter/viewa/$', views.view_appointment, name='viewa'),
]

publisher/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

publisher/forms.py
# -*- coding: utf-8 -*-
from django import forms
from . import utils


# Forms
class LoginForm(forms.Form):
    loginname=forms.CharField(min_length=4, label='用户名')
    password = forms.CharField(min_length=4, label='密码', widget=forms.PasswordInput())


class RegisterForm(forms.Form):
    loginname = forms.CharField(required=True, min_length=4, label='管理员登录名')
    password = forms.CharField(required=True, min_length=4, label='密码',widget=forms.PasswordInput())
    second_password = forms.CharField(required=True, min_length=4, label='再次输入密码',widget=forms.PasswordInput())
    telephone = forms.CharField(required=False, label='手机号(选填)')
    email = forms.EmailField(required=False, label='邮箱(选填)',widget=forms.EmailInput())
    hospital = forms.ChoiceField(required=True, label='所属医院', widget=forms.Select(),
                                 choices=utils.select_hospital())


# class BulletinForm(forms.Form):
#     fee = forms.DecimalField(required=True,label='预约费用')
#     available_time = forms.CharField(required=True, min_length=4,label='可预约时间')
#     count_available = forms.IntegerField(required=True, label='可预约人数')
#     count_occupied = forms.IntegerField(required=True, label='已预约人数')
#     department = forms.ChoiceField(required=True, label='医生所属科室', widget=forms.Select(),
#                                    choices=utils.getDepartments())
#     doctor = forms.ChoiceField(required=True, label='医生实名', widget=forms.Select(),
#                                choices=utils.getDoctors())


class BulletinForm(forms.Form):
    fee = forms.DecimalField(required=True, label='预约费用')
    available_time = forms.CharField(required=True, min_length=4, label='可预约时间')
    count_available = forms.IntegerField(required=True, label='可预约人数')
    count_occupied = forms.IntegerField(required=True, label='已预约人数')
    department = forms.IntegerField(required=True, label='医生所属科室', widget=forms.Select())
    doctor = forms.IntegerField(required=True, label='医生实名', widget=forms.Select())

    def __init__(self, *args, **kwargs):  # 执行父类的构造方法
        hospital_id = kwargs['hospital_id']
        kwargs.pop('hospital_id')

        super(BulletinForm, self).__init__(*args, **kwargs)
        self.fields['department'].widget.choices = utils.getDepartments(hospital_id)
        self.fields['doctor'].widget.choices = utils.getDoctors(hospital_id)


class FileForm(forms.Form):
    filefield = forms.FileField(required=True, label='请选择文件')
    # filepath = forms.FilePathField(required=True, label='请选择文件路径')

publisher/views.py
# coding:utf-8
from django.shortcuts import render, redirect
from django.http import HttpResponse
from forms import LoginForm, RegisterForm, FileForm, BulletinForm
from . import utils
import xlrd
from openpyxl.reader.excel import load_workbook
from django.db import models
from users import models
import datetime
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
import json

# Create your views here.
def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        publisher = utils.auth_publisher(form)
        if publisher:
            request.session['islogin'] = True
            request.session['loginname'] = form.cleaned_data['loginname']
            request.session['publisher_id'] = publisher[0].id_adminpublisher
            request.session['hospital_id'] = publisher[0].id_hospital_id
            request.session.set_expiry(3600)
            return redirect('/publisher')
        else:
            form = LoginForm()
            return render(request, 'publisher/login.html', {'form': form, 'error_message': '用户名或密码不正确'})
    else:
        form = LoginForm()
        return render(request, 'publisher/login.html', {'form': form})


def logout(request):
    request.session.clear()
    return redirect('/publisher/login/')


def success(request):
    return render(request, 'publisher/regsuccess.html')


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            if not form.cleaned_data['password'] == form.cleaned_data['second_password']:
                form = RegisterForm()
                return render(request, 'publisher/register.html', {'form': form, 'error_message': '两次密码输入不一致!'})
            elif utils.publisher_exists(form.cleaned_data['loginname']):
                return render(request, 'publisher/register.html', {'form': form, 'error_message': '用户名已存在!'})
            else:
                utils.add_publisher(form)
                return render(request, 'publisher/regsuccess.html')
        else:
            form = RegisterForm()
            return render(request, 'publisher/register.html', {'form': form, 'error_message': '请输入正确信息!'})
    else:
        form = RegisterForm()
        return render(request, 'publisher/register.html', {'form': form})


def index(request):
    session = request.session
    islogin = session.get('islogin', False)
    if islogin:
        bulletins = utils.select_all_bulletin(request.session['hospital_id'])
        if not bulletins:
            return render(request, 'publisher/index.html', {'loginname': session['loginname'], 'message': '尚未发布任何预约信息！'})
        return render(request, 'publisher/index.html', {'loginname': session['loginname'], 'bulletins': bulletins})
    else:
        return redirect('/publisher/login/')


#修改预约信息
def alter_bulletin(request):
    if request.method == 'POST':
        session = request.session
        form = BulletinForm(request.POST, hospital_id=session['hospital_id'])
        if form.is_valid():
            utils.alter_bulletin(form, session)
            return redirect('/publisher/')
    else:
        session = request.session
        session['id_bulletin'] = request.GET.get('id_bulletin',-1)
        fee = request.GET.get('fee', -1)
        availabletime = request.GET.get('availabletime', -1)
        countavailable = request.GET.get('countavailable', -1)
        countoccupied = request.GET.get('countoccupied', -1)
        department = request.GET.get('department',-1)
        doctor = request.GET.get('doctor',-1)
        form = BulletinForm(hospital_id=session['hospital_id'])
        return render(request, 'publisher/bulletin.html', {'loginname': session['loginname'],
                                                           'form': form,
                                                          'fee': fee,
                                                          'availabletime': availabletime,
                                                          'countavailable': countavailable,
                                                          'countoccupied': countoccupied,
                                                          'department': department,
                                                          'doctor': doctor,
                                                          'doctor_department': json.dumps(utils.get_doctor_department(
                                                               session['hospital_id']))
                                                           })


# 删除预约信息
def delete_bulletin(request, bulletin_id):
    models.Bulletin.objects.get(pk=bulletin_id).delete()
    return redirect('/publisher')


# 发布预约信息
def create_bulletin(request):
    session = request.session
    islogin = session.get('islogin', False)
    if not islogin:
        return redirect('/publisher/login')
    if request.method == 'POST':
        session = request.session
        form = BulletinForm(request.POST, hospital_id=session['hospital_id'])
        if form.is_valid():
            utils.create_bulletin(form,session)
            return redirect('/publisher/')
        else:
            error_message = '您填写的信息有错误，请重新填写！'
            return render(request, 'publisher/bulletin.html',
                          {'loginname': request.session['loginname'],
                           'form': form, 'error_message': error_message,
                           'doctor_department': json.dumps(utils.get_doctor_department(
                               session['hospital_id']))
                           })
    else:
        form= BulletinForm(hospital_id=session['hospital_id'])
        return render(request, 'publisher/bulletin.html',
                      {'loginname': request.session['loginname'],
                       'form': form,
                       'doctor_department': json.dumps(utils.get_doctor_department(session['hospital_id']))
                     })


def batch_import_bulletin_by_excel(request):
    if request.method == 'POST':
        form = FileForm(request.POST, request.FILES)
        if form.is_valid():
            if request.FILES['filefield'].name.split('.')[-1] == 'xlsx':
                try:
                    utils.handle_uploaded_file(request, f=request.FILES['filefield'])
                except ObjectDoesNotExist, e:
                    error_message = '科室和医生组合不存在，请检查所上传表格内容后重新上传'
                    return render(request, 'publisher/file.html',
                                  {'form': form, 'error_message': error_message,
                                   'loginname': request.session['loginname']})
                return render(request, 'publisher/file.html',
                              {'form': form, 'error_message': '上传成功！',
                               'loginname': request.session['loginname']})
            else:
                error_message = '文件格式错误，请上传Excel文件（.xlsl)'
                form = FileForm()
                return render(request, 'publisher/file.html', {'form': form, 'error_message': error_message, 'loginname': request.session['loginname']})
    else:
        form = FileForm()
        return render(request, 'publisher/file.html', {'form': form, 'loginname': request.session['loginname']})

publisher/templates/publisher/file.html
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    {% load static %}
<meta charset="utf-8">
<title>批量导入</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1" name="viewport">
<meta content="" name="description">
<meta content="" name="author">
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css">
<link href="{% static 'assets/global/plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'assets/global/plugins/simple-line-icons/simple-line-icons.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'assets/global/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'assets/global/plugins/uniform/css/uniform.default.css' %}" rel="stylesheet" type="text/css">
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
<link href="{% static 'assets/global/plugins/morris/morris.css' %}" rel="stylesheet" type="text/css">
<!-- END PAGE LEVEL PLUGIN STYLES -->
<!-- BEGIN PAGE STYLES -->
<link href="{% static 'assets/admin/pages/css/tasks.css' %}" rel="stylesheet" type="text/css"/>
<!-- END PAGE STYLES -->
<!-- BEGIN THEME STYLES -->
<!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->
<link href="{% static 'assets/global/css/components-rounded.css' %}" id="style_components" rel="stylesheet" type="text/css">
<link href="{% static 'assets/global/css/plugins.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'assets/admin/layout3/css/layout.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'assets/admin/layout3/css/themes/test.css' %}" rel="stylesheet" type="text/css" id="style_color">
<link href="{% static 'assets/admin/layout3/css/custom.css' %}" rel="stylesheet" type="text/css">
<!-- END THEME STYLES -->
<link rel="shortcut icon" href="favicon.ico">
</head>
<!-- BEGIN BODY -->
<!-- DOC: Apply "page-header-menu-fixed" class to set the mega menu fixed  -->
<!-- DOC: Apply "page-header-top-fixed" class to set the top menu fixed  -->
<body>
<!-- BEGIN HEADER -->
<div class="page-header">
	<!-- BEGIN HEADER TOP -->
	<div class="page-header-top">
		<div class="container">
			<!-- BEGIN LOGO -->
			<div class="page-logo">
				<a href="{% url 'publisher:index' %}"><img src="{% static 'assets/admin/layout3/img/logo-default.png' %}" alt="logo" class="logo-default"></a>
			</div>
			<!-- END LOGO -->
			<!-- BEGIN RESPONSIVE MENU TOGGLER -->
			<a href="javascript:;" class="menu-toggler"></a>
			<!-- END RESPONSIVE MENU TOGGLER -->
			<!-- BEGIN TOP NAVIGATION MENU -->
			<div class="top-menu">
				<ul class="nav navbar-nav pull-right">


					<li class="droddown dropdown-separator">
						<span class="separator"></span>
					</li>

					<!-- BEGIN USER LOGIN DROPDOWN -->
					<li class="dropdown dropdown-user dropdown-dark">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
						<img alt="" class="img-circle" src="{% static 'assets/admin/layout3/img/avatar9.jpg' %}">
						<span class="username username-hide-mobile">{{ loginname }}</span>
						</a>
						<ul class="dropdown-menu dropdown-menu-default">
							<li>
								<a href="{% url 'publisher:logout' %}">
								<i class="icon-logout"></i> 注销登录 </a>
							</li>
						</ul>
					</li>
					<!-- END USER LOGIN DROPDOWN -->
				</ul>
			</div>
			<!-- END TOP NAVIGATION MENU -->
		</div>
	</div>
	<!-- END HEADER TOP -->
	<!-- BEGIN HEADER MENU -->
	<div class="page-header-menu">
		<div class="container">
			<!-- BEGIN MEGA MENU -->
			<!-- DOC: Apply "hor-menu-light" class after the "hor-menu" class below to have a horizontal menu with white background -->
			<!-- DOC: Remove data-hover="dropdown" and data-close-others="true" attributes below to disable the dropdown opening on mouse hover -->
			<div class="hor-menu ">
				<ul class="nav navbar-nav">
					<li class="menu-dropdown">
						<a href="{% url 'publisher:create' %}" class="tooltips" data-container="body" data-placement="bottom" data-html="true" data-original-title="发布预约信息">
						发布预约信息</a>
					</li>
					<li class="menu-dropdown">
						<a href="{% url 'publisher:batchUpload' %}" class="tooltips" data-container="body" data-placement="bottom" data-html="true" data-original-title="批量发布">
						批量发布</a>
					</li>
					<li class="menu-dropdown">
						<a href="{% url 'publisher:index' %}" class="tooltips" data-container="body" data-placement="bottom" data-html="true" data-original-title="已发布预约信息">
						已发布预约信息</a>
					</li>
				</ul>
			</div>
			<!-- END MEGA MENU -->
		</div>
	</div>
	<!-- END HEADER MENU -->
</div>
<!-- END HEADER -->
<div class="page-container">
	<div class="page-head">
		<div class="container">
			<div class="page-title">
				<h1>批量发布预约信息</h1>
			</div>
		</div>
	</div>

	<div class="page-content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
						<!-- BEGIN EXAMPLE TABLE PORTLET-->
						<div class="portlet light">
							<div class="portlet-title">
								<div class="caption">
									<i class="fa fa-cogs font-green-sharp"></i>
									<span class="caption-subject font-green-sharp bold uppercase">选择预约信息批量发布</span>
								</div>
							</div>
                            {% if error_message %}
                                <div id="error_message" style="color: red;font-family: 等线;font-size: 20px;">{{ error_message }}</div>
                            {% endif %}
							<div class="portlet-body">
								<form id="fileupload" method="POST" enctype="multipart/form-data">
								<!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
								<div class="row fileupload-buttonbar">
									<div class="col-lg-7">
										<!-- The fileinput-button span is used to style the file input field as button -->
										<span class="btn green fileinput-button">
										<i class="fa fa-plus"></i>
										<span>
										选择文件 </span>
										{{ form.filefield }}
										</span>
                                        {% csrf_token %}
										<button type="submit" class="btn blue start">
										<i class="fa fa-upload"></i>
										<span>
										开始上传 </span>
										</button>

									</div>
									<!-- The global progress information -->
									<div class="col-lg-5 fileupload-progress fade">
										<!-- The global progress bar -->

										<!-- The extended global progress information -->
										<div class="progress-extended">
											 &nbsp;
										</div>
									</div>
								</div>
								<!-- The table listing the files available for upload/download -->
								<table role="presentation" class="table table-striped clearfix">
								<tbody class="files">
								</tbody>
								</table>
							</form>
							</div>
						</div>
					<!-- END EXAMPLE TABLE PORTLET-->
				</div>
			</div>
		</div>
	</div>
</div>

<!-- BEGIN JAVASCRIPTS (Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="{% static 'assets/global/plugins/respond.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/excanvas.min.js' %}"></script>
<![endif]-->
<script src="{% static 'assets/global/plugins/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery-migrate.min.js' %}" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="{% static 'assets/global/plugins/jquery-ui/jquery-ui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery.blockui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery.cokie.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/uniform/jquery.uniform.min.js' %}" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- IMPORTANT! fullcalendar depends on jquery-ui.min.js for drag & drop support -->
<script src="{% static 'assets/global/plugins/morris/morris.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/morris/raphael-min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery.sparkline.min.js' %}" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{% static 'assets/global/scripts/metronic.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/layout3/scripts/layout.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/layout3/scripts/demo.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/pages/scripts/index3.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/pages/scripts/tasks.js' %}" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
    $('.btn.blue.start').click(function () {
        if($('#id_filefield').val()){
            return true;
        }else{
            alert('文件不能为空，请选择文件！');
            return false;
        }
    });
jQuery(document).ready(function() {
   Metronic.init(); // init metronic core componets
   Layout.init(); // init layout
   Demo.init(); // init demo(theme settings page)
   QuickSidebar.init(); // init quick sidebar
   Index.init(); // init index page
   Tasks.initDashboardWidget(); // init tash dashboard widget
});
</script>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>

publisher/templates/publisher/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    {% load static %}

    <meta charset="utf-8"/>
<title>预约信息发布管理员登录</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta content="" name="description"/>
<meta content="" name="author"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
<link href="{% static  'assets/global/plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/simple-line-icons/simple-line-icons.min.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/plugins/uniform/css/uniform.default.css' %}" rel="stylesheet" type="text/css"/>
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<link href="{% static 'assets/admin/pages/css/login.css' %}" rel="stylesheet" type="text/css"/>
<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN THEME STYLES -->
<link href="{% static 'assets/global/css/components-rounded.css' %}" id="style_components" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/global/css/plugins.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/admin/layout/css/layout.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/admin/layout/css/themes/default.css' %}" rel="stylesheet" type="text/css" id="style_color"/>
<link href="{% static 'assets/admin/layout/css/custom.css' %}" rel="stylesheet" type="text/css"/>
<!-- END THEME STYLES -->
<link rel="shortcut icon" href="favicon.ico"/>

</head>
<body class="login">
<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
<div class="menu-toggler sidebar-toggler">
</div>
<!-- END SIDEBAR TOGGLER BUTTON -->
<!-- BEGIN LOGO -->
<div class="logo">
	<img src="{% static 'assets/admin/layout3/img/logo-big.png' %}" alt=""/>
</div>
<!-- END LOGO -->
<!-- BEGIN LOGIN -->

<div class="content" >
	<!-- BEGIN LOGIN FORM -->
	<form novalidate="novalidate" class="login-form"  method="post">
		<h3 class="form-title">预约信息发布管理员 登录</h3>
		<div class="alert alert-danger display-hide">
			<button class="close" data-close="alert"></button>
			<span>请输入密码！</span>
		</div>
		<div class="form-group">
			<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
			<label class="control-label visible-ie8 visible-ie9">用户名</label>
            {{ form.loginname }}
{#			<input class="form-control form-control-solid placeholder-no-fix" autocomplete="off" placeholder="用户名" name="username" type="text">#}
		</div>
		<div class="form-group">
			<label class="control-label visible-ie8 visible-ie9">密码</label>
            {{ form.password }}
		</div>
		<div class="form-actions">
            {% csrf_token %}
			<button type="submit" class="btn btn-success uppercase">登陆</button>
            {% if error_message %}
                <div id="error" style="color: #ff383a;position: absolute;font-family: '微软雅黑 Light';font-size: large;margin-left: 80px;top: 210px;font-weight: bold">
                    {{ error_message }}</div>
            {% endif %}
		</div>
		<div class="create-account">
			<p>
				<a href="{% url 'publisher:register' %}" id="register-btn" class="uppercase">预约信息发布管理员用户注册</a>
			</p>
		</div>
	</form>

	</div>

<script src="{% static 'assets/global/plugins/respond.min.js' %}"></script>
<script src="{% static 'assets/global/plugins/excanvas.min.js' %}"></script>
<![endif]-->
<script src="{% static 'assets/global/plugins/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery-migrate.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery.blockui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/uniform/jquery.uniform.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/global/plugins/jquery.cokie.min.js' %}" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="{% static 'assets/global/plugins/jquery-validation/js/jquery.validate.min.js' %}" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{% static 'assets/global/scripts/metronic.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/layout/scripts/layout.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/layout/scripts/demo.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/admin/pages/scripts/login.js' %}" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
    var form_input  = $('form input');
    form_input.addClass('form-control form-control-solid placeholder-no-fix');
    form_input.attr('autocomplete', 'off');
    $(form_input[0]).attr('placeholder', '用户名');
    $(form_input[1]).attr('placeholder', '密码');
jQuery(document).ready(function() {
	Metronic.init(); // init metronic core components
	Layout.init(); // init current layout
	Login.init();
	Demo.init();
});

</script>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>

publisher/templates/publisher/regsuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册成功</title>
</head>
<body>
<div style="color: red;font-family: 等线;font-size: 20px;text-align: center;">注册成功!</div>
{#<a href="{% url 'publisher:login' %}">立即登录</a>#}
<div id="ShowDiv" style="color: black;font-family: 等线;font-size: 15px;text-align: center;margin-top: 20px;"></div>

</body>
<script language="javascript">
var secs = 3; //倒计时的秒数
var URL = "{% url 'publisher:login'%}";
function Load(){
    for(var i=secs;i>=0;i--)
    {
       window.setTimeout('doUpdate(' + i + ')', (secs-i) * 1000);
    }
}
function doUpdate(num)
{
    document.getElementById('ShowDiv').innerHTML = "将在<span style='color: red;font-size: 20px;'>"
            + num + "</span>秒后自动跳转到登录页面..." ;
    if(num == 0) { window.location = URL; }
}
Load();
</script>
</html>