users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^hospital/$', views.hospital, name='hospital'),
    url(r'^department/$', views.department, name='department'),
    url(r'^test/$', views.test, name='test'),
    url(r'^doctor/$', views.doctor, name='doctor'),
    url(r'^reservation/$', views.reservation, name='reservation'),
    url(r'^usercenter/$', views.user_center, name='usercenter'),
    url(r'^usercenter/changeinfo/$', views.change_info, name='changeinfo'),
    url(r'^usercenter/accountsafe/$', views.change_pw, name='accountsafe'),
    url(r'^usercenter/viewa/$', views.view_appointment, name='viewa'),
]

users/forms.py
# -*- coding: utf-8 -*-
from django import forms


# Forms
class RegisterForm(forms.Form):
    username = forms.CharField(min_length=4, label='用户名')
    password = forms.CharField(min_length=4, label='密码', widget=forms.PasswordInput())
    second_password = forms.CharField(min_length=4, label='再次输入密码', widget=forms.PasswordInput())
    telephone = forms.CharField(required=False, label='手机号(选填)')
    email = forms.EmailField(required=False, label='邮箱(选填)', widget=forms.EmailInput())
    name = forms.CharField(label='真实姓名')
    # debug mode
    idcardnumber = forms.CharField(max_length=18, label='18位合法身份证号')
    GENDER = (
        (0, '男'),
        (1, '女')
    )
    gender = forms.ChoiceField(choices=GENDER, label='性别')
    age = forms.IntegerField(min_value=0, max_value=150, label='年龄')


class LoginForm(forms.Form):
    username = forms.CharField(min_length=4, label='用户名')
    password = forms.CharField(min_length=4, label='密码', widget=forms.PasswordInput())


class ChangePWForm(forms.Form):
    oldpassword = forms.CharField(max_length=32, label='旧密码')
    newpassword1 = forms.CharField(max_length=32, label='新密码')
    newpassword2 = forms.CharField(max_length=32, label='确认密码')

    def clean(self):
        if not self.is_valid():
            raise forms.ValidationError(u"所有项都为必填项")
        elif self.cleaned_data['newpassword1'] != self.cleaned_data['newpassword2']:
            raise forms.ValidationError(u"两次输入的新密码不一样")
        else:
            cleaned_data = super(ChangePWForm, self).clean()
        return cleaned_data

users/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import RegisterForm, LoginForm,ChangePWForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

from . import models
from . import utils

provinces = ['河北', '陕西', '辽宁', '吉林', '黑龙江', '江苏', '浙江', '安徽', '福建', '江西', '山东', '河南', '湖北', '湖南', '广东'
    , '海南', '四川', '贵州', '云南', '陕西', '甘肃', '青海', '北京', '天津', '上海', '重庆', '内蒙古', '广西', '宁夏', '新疆', '西藏']
provinces.sort()


# 在需要鉴别用户身份的地方，调用request.user.is_authenticated()判断即可
# 需要用户登录才能访问的页面，请添加header @login_required(login_url='login'),参见test
# Create your views here.
def index(request):
    province = request.GET.get('province', None)
    city = request.GET.get('city', None)
    hospitals = None
    cities = None
    if city:
        hospitals = utils.getHospitals(city)
    elif province:
        cities = utils.getCities(province)
    return render(request, 'users/index.html', {'username': request.user.username, 'provinces': provinces
        , 'cities': cities, 'hospitals': hospitals})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if not form.is_valid():
            form = LoginForm()
            return render(request, 'users/login.html', {'form': form, 'error_message': '用户名或密码不正确'})
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                auth_login(request, user)
                next = request.GET.get('next', None)
                if next:
                    return redirect(next)
                return redirect('/users')
            else:
                return HttpResponse('您的账户已被禁用')
        else:
            form = LoginForm()
            return render(request, 'users/login.html', {'form': form, 'error_message': '用户名或密码不正确'})
    else:
        form = LoginForm()
        return render(request, 'users/login.html', {'form': form})


def logout(request):
    auth_logout(request)
    return render(request,'users/logout.html')


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            if not form.cleaned_data['password'] == form.cleaned_data['second_password']:
                form = RegisterForm()
                return render(request, 'users/register.html', {'form': form, 'error_message': '两次密码输入不一致!'})
            else:
                utils.addUser(form)
                return render(request, 'users/regsuccess.html')
        else:
            form = RegisterForm()
            return render(request, 'users/register.html', {'form': form, 'error_message': '请输入正确信息!'})
    else:
        form = RegisterForm()
        return render(request, 'users/register.html', {'form': form})


class Item:
    doctor=None
    bulletin=None
    department=None

    def __init__(self,doctor,bulletin,department):
        self.doctor=doctor
        self.bulletin=bulletin
        self.department=department


def department(request):
    return HttpResponse('department')


def hospital(request):
    hospital_id = request.GET.get('hospital_id', None)
    department_id=request.GET.get('department_id',None)
    hospital = models.Hospital.objects.filter(id_hospital=hospital_id).first()
    departments = models.Department.objects.filter(id_hospital=hospital_id)
    if department_id:
        location = models.Location.objects.filter(id_location=hospital.id_location.id_location).first()
        bulletins=utils.getBulletins(department_id)
        doctors=utils.getDoctors(bulletins)
        department=models.Department.objects.filter(id_department=department_id).first()
        items=[]
        for i in range(len(bulletins)):
            item=Item(doctor=doctors[i],bulletin=bulletins[i],department=department)
            items.append(item)
        return render(request, 'users/hospital.html',
                      {'username': request.user.username, 'hospital': hospital, 'location': location,'departments':departments,'items':items})
    else:
        return render(request,'users/hospital.html',{'username': request.user.username, 'hospital': hospital,'departments':departments})



@login_required(login_url='login')
def test(request):
    return HttpResponse('Test page')


def doctor(request):
    doctor_id=request.GET.get('doctor_id',1)
    bulletin_id=request.GET.get('bulletin_id',1)
    department_id=request.GET.get('department_id',1)
    doctor=models.Doctor.objects.filter(id_doctor=doctor_id).first()
    bulletin=models.Bulletin.objects.filter(id_bulletin=bulletin_id).first()
    department=models.Department.objects.filter(id_department=department_id).first()
    return render(request,'users/doctor.html',{'username':request.user.username,'doctor':doctor,'bulletin':bulletin
        ,'department':department})


@login_required(login_url='login')
def reservation(request):
    doctor_id = request.GET.get('doctor_id', 1)
    bulletin_id = request.GET.get('bulletin_id', 1)
    department_id = request.GET.get('department_id', 1)
    doctor = models.Doctor.objects.filter(id_doctor=doctor_id).first()
    bulletin = models.Bulletin.objects.filter(id_bulletin=bulletin_id).first()
    department = models.Department.objects.filter(id_department=department_id).first()
    if request.method=='POST':
        if utils.addAppointment(bulletin,request.user.username):
            return HttpResponse('预约成功')
        else:
            return HttpResponse('您已成功预约，无需重复预约')
    return render(request,'users/reservation.html',{'username':request.user.username
        ,'doctor':doctor,'bulletin':bulletin,'department':department})


@login_required(login_url='login')
def user_center(request):
    username = request.user.username
    # print(username)
    # userhere = models.Patient.objects.filter(username='useruser').first()
    # it should be :
    userhere = models.Patient.objects.filter(username=username).first()
    # print(userhere)
    name = userhere.name
    sex = userhere.gender
    age = userhere.age
    idcn = userhere.idcardnumber
    tele = userhere.telephone
    email = userhere.email
    credit = userhere.credit
    return render(request, 'users/usercenter.html', {'wholename': name, 'sex': sex, 'age': age,
    'idcn':idcn,'tel':tele,'mail':email,'credit':credit
    })

@login_required(login_url='login')
def change_info(request):
    pass

@login_required(login_url='login')
def change_pw(request):
    if request.method == 'GET':
        form = ChangePWForm()
        return render(request,'users/changepwd.html', {'form': form})
    elif request.method == 'POST':
        form = ChangePWForm(request.POST)
        if form.is_valid():
            username = request.user.username
            oldpassword = request.POST.get('oldpassword', '')
            user = authenticate(username=username, password=oldpassword)
            if user is not None and user.is_active:
                newpassword = request.POST.get('newpassword1', '')
                utils.change_password(newpassword,username)
                return render(request,'users/changepwd.html', {'changepwd_success': True})
            else:
                return render(request,'users/changepwd.html',
                                         {'form': form, 'oldpassword_is_wrong': True})
        else:
            return render(request,'users/changepwd.html', {'form': form})

@login_required(login_url='login')
def view_appointment(request):
    pass

users/templates/users/changeinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

users/templates/users/changepwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>修改密码</title>
    <meta name="description" content="">
    <meta name="author" content="zy">
</head>

<body>
{% if oldpassword_is_wrong %}
    <div class="alert alert-error">
        <h4>错误!</h4>原密码不正确，请重新填写！
    </div>
{% endif %}
{% if changepwd_success %}
    <div class="alert alert-error">
        <h4>修改成功！</h4>
    </div>
{% endif %}
    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>
        {% csrf_token %}
        <input type="submit" value="确认修改">
    </form>
    <a href="{% url 'user:usercenter' %}">返回用户中心</a>
</body>
</html>

users/templates/users/department.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

users/templates/users/doctor.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>医生信息</title>
</head>
<body>
{% if username %}
    你好，{{ username }}
    <a href="{% url 'users:logout' %}">注销</a></br>
{% else %}
    <a href="{% url 'users:login' %}">登录</a></br>
{% endif %}
{% if doctor %}
    {% if doctor.picture %}
        {% load static %}
        <img src="{% static doctor.picture %}"/></br>
        {% endif %}
    {{ doctor.name }} </br>
    {{ doctor.gender }}
    {{ doctor.level }} </br>
    从医时间: {{ doctor.careertime}} 年</br>
    个人信息: {{ doctor.information }} </br>
{% endif %}
</body>
</html>

users/templates/users/hospital.html
<!DOCTYPE html>
<br lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>医院信息</title>
</head>
{% if username %}
    你好，{{ username }}
    <a href="{% url 'users:logout' %}">注销</a></br>
{% else %}
    <a href="{% url 'users:login' %}">登录</a></br>
{% endif %}
{{ hospital.name }} </br>
{{ hospital.level }} </br>
电话:{{ hospital.telephone }} </br>
{{ hospital.information }} </br>
地址:{{ location.province }} {{ location.city }} {{ location.street }} </br>

{% if hospital.picture %}
    {% load static %}
    <img src="{% static hospital.picture %}"/></br>
{% endif %}
请先选择科室 </br>
{% for department in departments %}
    <a href="?hospital_id={{ hospital.id_hospital }}&department_id={{ department.id_department }}">{{ department.name }}</a>
{% endfor %} </br>

{% if items %}
    <table>
        <tr>
            <td>医生</td>
            <td>科室</td>
            <td>等级</td>
            <td>预约时间</td>
            <td>可预约数量</td>
            <td>已预约数量</td>
            <td>预约费用</td>
            <td>预约</td>
        </tr>
    {% for item in items%}
             <tr>
                <td><a href="{% url 'users:doctor' %}?doctor_id={{ item.doctor.id_doctor }}&bullet_id={{ item.bulletin.id_bulletin }}&department_id={{ item.department.id_department }}">{{ item.doctor.name }}</a></td>
                <td>{{ item.department.name }}</td>
                <td>{{ item.doctor.level }}</td>
                <td>{{ item.bulletin.availabletime }}</td>
                <td>{{ item.bulletin.countavailable }}</td>
                <td>{{ item.bulletin.countoccupied }}</td>
                <td>{{ item.bulletin.fee }}</td>
                 {% if username %}
                     {% if item.bulletin.countavailable > item.bulletin.countoccupied %}
                         <td><a href="{% url 'users:reservation' %}?doctor_id={{ item.doctor.id_doctor }}&bulletin_id={{ item.bulletin.id_bulletin }}&department_id={{ item.department.id_department }}">点击预约</a></td>
                         {% else %}
                         <td>名额已满，无法预约</td>
                         {% endif %}
                {% else %}
                <td><a href="{% url 'users:login' %}">登录</a></td>
                {% endif %}
            </tr>
    {% endfor %}
    </table>
    {% else %}
    当前没有可以预约的医生
{% endif %}
</body>
</html>

users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    {% if username %}
         你好，{{ username }}
        <a href="{% url 'users:logout' %}">注销</a></br>
        <a href="{% url 'users:usercenter' %}">用户中心</a></br>
    {% else %}
        <a href="{%  url 'users:login' %}">登录</a></br>
    {% endif %}

    选择省份</br>
    {% for province in provinces %}
    <a href="?province={{ province }}">{{ province }}</a>
    {% endfor %}
    </br>
    {% if cities %}
        </br>选择城市</br>
        {% for city in cities %}
             <a href="?city={{ city }}">{{ city }}</a>
        {% endfor %}
    {% endif %}
    {% if hospitals %}
        </br>选择医院</br>
        {% for hospital in hospitals %}
            <a href="{% url 'users:hospital' %}?hospital_id={{ hospital.id_hospital }}">{{ hospital.name }}</a>
        {% endfor %}
    {% endif %}
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
    {% if error_message %}
        {{ error_message }}
    {% endif %}
    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>
        {% csrf_token %}
        <input type="submit" value="登录"></br>
        <a href="{% url 'users:register' %}">没有账户?</a>
    </form>
</body>
</html>

users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注销</title>
</head>
<body>
注销成功~</br>
<a href="{% url 'users:login' %}" >前往登录页</a>
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
    {% if error_message %}
        {{ error_message }}
    {% endif %}
    <form action="" method="post">
        <table>
            {{ form.as_table }}
        </table>
        {% csrf_token %}
        <input type="submit" value="提交"></br>
        <a href="{% url 'users:login' %}">已有账号？立即登录</a>
    </form>
</body>
</html>

users/templates/users/regsuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册成功</title>
</head>
<body>
注册成功~</br>
<a href="{% url 'users:login' %}">立即登录</a>
</body>
</html>

users/templates/users/reservation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>预约</title>
</head>
<body>
 <a href="{% url 'users:logout' %}">注销</a></br>
医生姓名:{{ doctor.name }} </br>
医生评级:{{ doctor.level }} </br>
科室:{{ department.name }} </br>
预约时间:{{ bulletin.availabletime }} </br>
预约费用:{{ bulletin.fee }} </br>

<form method="post" action="" >
    <input type="submit" value="预约">
    {% csrf_token %}
</form>

</body>
</html>

users/templates/users/usercenter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户中心</title>
    <h1>用户中心</h1>
    <p>名字：{{ wholename }}</p>
    <p>性别：{{ sex }}</p>
    <p>年龄：{{ age }}</p>
    <p>电话：{{ tel }}</p>
    <p>电子邮箱：{{ mail }}</p>
    <p>身份证号：{{ idcn }}</p>
    <p>信用等级：{{ credit }}</p>
    <a href="/">返回主页</a>
    <a href="{% url 'user:viewa' %}">查看订单</a>
    <a href="{% url 'user:changeinfo' %}">修改信息</a>
{#    <a href=""></a>#}
    <a href="{% url 'user:accountsafe' %}">账号安全</a>
    <a href="{% url 'user:logout' %}">注销</a></br>
</head>
<body>

</body>
</html>